events {}
http {
    include mime.types;
    server {
        listen 80;
        location /editor/ {
            proxy_pass http://app:5000;
            proxy_set_header Host $host;
        }
    }
}
